// io.c

#include <stdio.h>

#include "board.h"
#include "misc.h"
#include "move.h"
#include "movegen.h"
#include "transposition.h"
#include "validate.h"


// Translates a move to a string
char *MoveToStr(const int move) {

	static char moveStr[6];
	char pchar;

	int ff = fileOf(FROMSQ(move));
	int rf = rankOf(FROMSQ(move));
	int ft = fileOf(TOSQ(move));
	int rt = rankOf(TOSQ(move));

	int promo = pieceTypeOf(PROMOTION(move));

	if (promo) {

		if (     promo == QUEEN)
			pchar = 'q';
		else if (promo == KNIGHT)
			pchar = 'n';
		else if (promo == ROOK)
			pchar = 'r';
		else		   // BISHOP
			pchar = 'b';

		sprintf(moveStr, "%c%c%c%c%c", ('a' + ff), ('1' + rf), ('a' + ft), ('1' + rt), pchar);
	} else
		sprintf(moveStr, "%c%c%c%c", ('a' + ff), ('1' + rf), ('a' + ft), ('1' + rt));

	return moveStr;
}

// Translates a string to a move
// a2a4 b7b8q g7f8n
int ParseMove(const char *ptrChar, Position *pos) {

	assert(CheckBoard(pos));

	// Make sure coordinates make sense (should maybe give an error)
	if (ptrChar[1] > '8' || ptrChar[1] < '1') return NOMOVE;
	if (ptrChar[3] > '8' || ptrChar[3] < '1') return NOMOVE;
	if (ptrChar[0] > 'h' || ptrChar[0] < 'a') return NOMOVE;
	if (ptrChar[2] > 'h' || ptrChar[2] < 'a') return NOMOVE;

	// Translate coordinates into square numbers
	int from = (ptrChar[0] - 'a') + (8 * (ptrChar[1] - '1'));
	int to   = (ptrChar[2] - 'a') + (8 * (ptrChar[3] - '1'));

	MoveList list[1];
	GenAllMoves(pos, list);

	// Make sure the move is legal in the current position
	// by checking that it is generated by movegen
	for (unsigned int moveNum = 0; moveNum < list->count; ++moveNum) {

		int move = list->moves[moveNum].move;

		if (FROMSQ(move) == from && TOSQ(move) == to) {

			int promo = pieceTypeOf(PROMOTION(move));

			if (promo) {

				if (     promo == QUEEN  && ptrChar[4] == 'q')
					return move;
				else if (promo == KNIGHT && ptrChar[4] == 'n')
					return move;
				else if (promo == ROOK   && ptrChar[4] == 'r')
					return move;
				else if (promo == BISHOP && ptrChar[4] == 'b')
					return move;

				continue;
			}
			return move;
		}
	}
	return NOMOVE;
}

#ifdef DEV
// Translates a string from an .epd file to a move
// Nf3-g1+, f3-g1+, Nf3-g1, f3-g1N+
int ParseEPDMove(const char *ptrChar, Position *pos) {

	assert(CheckBoard(pos));

	// Skip piece indicator as it's not needed
	if ('B' <= ptrChar[0] && ptrChar[0] <= 'R')
		ptrChar++;

	// Make sure coordinates make sense (should maybe give an error)
	if (ptrChar[1] > '8' || ptrChar[1] < '1') return NOMOVE;
	if (ptrChar[4] > '8' || ptrChar[4] < '1') return NOMOVE;
	if (ptrChar[0] > 'h' || ptrChar[0] < 'a') return NOMOVE;
	if (ptrChar[3] > 'h' || ptrChar[3] < 'a') return NOMOVE;

	// Translate coordinates into square numbers
	int from = (ptrChar[0] - 'a') + (8 * (ptrChar[1] - '1'));
	int to   = (ptrChar[3] - 'a') + (8 * (ptrChar[4] - '1'));

	// Make sure the move is legal in the current position
	// by checking that it is generated by movegen
	MoveList list[1];
	GenAllMoves(pos, list);

	for (unsigned int moveNum = 0; moveNum < list->count; ++moveNum) {

		int move = list->moves[moveNum].move;

		if (FROMSQ(move) == from && TOSQ(move) == to) {

			int promo = pieceTypeOf(PROMOTION(move));

			if (promo) {

				if (     promo == QUEEN  && ptrChar[5] == 'Q')
					return move;
				else if (promo == KNIGHT && ptrChar[5] == 'N')
					return move;
				else if (promo == ROOK   && ptrChar[5] == 'R')
					return move;
				else if (promo == BISHOP && ptrChar[5] == 'B')
					return move;

				continue;
			}
			return move;
		}
	}
	return NOMOVE;
}
#endif